<?php
/**
 * Stored plugin settings (dashboard URL + API key).
 */
if ( ! defined( 'ABSPATH' ) ) exit;

class Leads_Sync_Settings {

	const OPTION_KEY = 'leads_sync_settings';

	public static function init() {
		// noop — options are read on demand.
	}

	public static function get() {
		$defaults = array(
			'endpoint'       => '',   // e.g. https://dashboard.example.com
			'api_key'        => '',   // per-site key generated by the dashboard
			'last_sync_at'   => 0,
			'last_sync_count'=> 0,
		);
		return wp_parse_args( get_option( self::OPTION_KEY, array() ), $defaults );
	}

	public static function save( array $new ) {
		$current = self::get();
		update_option( self::OPTION_KEY, array_merge( $current, $new ) );
	}

	public static function endpoint() {
		return untrailingslashit( self::get()['endpoint'] );
	}

	public static function api_key() {
		return self::get()['api_key'];
	}

	public static function is_configured() {
		$s = self::get();
		return ! empty( $s['endpoint'] ) && ! empty( $s['api_key'] );
	}
}
